# "[LinearAlgebra] CH01. Linear Equations and Inverse Matrices"
> Linear algebra summary note.

- toc: false
- badges: false
- comments: false
- categories: [linear-algebra]
- hide_{github,colab,binder,deepnote}_badge: true

#### 1.0. Elementary Definitions and Theorems

- 이 노트에서 사용하는 수학 표기는 [표기법](https://ndo04343.github.io/blog/math/math)을 따른다. 
- 기본적인 행렬의 연산과 성질들은 생략한다.

##### Definition.1.1. Matrix
임의의 자연수 $m$과 $n$에 대하여 $mn$개의 수 $(a_{ij} \in \mathbb{K}, \,\ i = 1, 2, \cdots, m, \,\ j = 1, 2, \cdots, n)$를 다음과 같이 배열한 도식(diagram) $A$를 $m \times n$ 행렬(matrix)이라고 한다. 

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1j} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2j} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots &  & \vdots \\
a_{i1} & a_{i2} & \cdots & a_{ij} & \cdots & a_{in} \\
\vdots & \vdots &  & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mj} & \cdots & a_{mn} \\
\end{bmatrix}
$$
행렬 $A$를 간단히 $A = [a_{ij}]$ 또는 $A = [a_{ij}]_{m \times n}$과 같이 나타낸다.

이 글에서 행렬과 관련된 기본 정의와 정리들은 위의 표기를 따른다.

#### 1.1. System of Linear Equations

##### Definition.1.2. Augmented Matrices and Coefficient Matrices
$n$개의 미지수 $x_1, \,\ x_2, \,\ \cdots, \,\ x_n$에 관한 연립일차방정식

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\; \vdots  \\
a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n = b_m \\
\end{cases},
$$

에 대하여

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{bmatrix}_{m \times n}, \mathbf{x} = \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n} \\
\end{bmatrix}_{n \times 1}, \text{and} \,\ \mathbf{b} = \begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{m} \\
\end{bmatrix}_{m \times 1}
$$

로 둘때, 연립일차방정식을 행렬을 써서 나타내면

$$
A\mathbf{x} = \mathbf{b}
$$

이다. \
\
이때, 연립일차방정식에  대응되는 행렬 $[A \quad \mathbf{b}]_{m \times (n + 1)}$를 주어진 연립일차방정식의 첨가행렬(Augmented matrix)이라고 하고 $A$를 연립일차방정식의 계수행렬(Coeffficient matrix)이라고 한다.



##### Theorem.1.1.
$A = [a_{ij}]_{n \times n}, \text{and} \,\ B = [b_{ij}]_{n \times n}$에 대하여 다음이 성립한다.

$$
\qquad (AB)^\top = B^\top A^\top
$$

__Proof.__ <br>
Trivial.

##### Theorem.1.2.
Let $A$ is invertible and have $n$-degree.

$$
\qquad (A^\top)^{-1} = (A^{-1})^\top
$$

__Proof.__ <br>
Trivial.

##### Theorem.1.3.
Square matrix $A$에 대하여, 다음이 성립한다.

$$
\text{(1)} \quad \text{If} \,\ [A \quad I] \cong_R [I \quad P], \,\ \text{then} \,\ P = A^{-1} \\
\text{(2)} \quad \text{If} \,\ \begin{bmatrix} A \\ I \end{bmatrix} \cong_C \begin{bmatrix} I \\ P \end{bmatrix}, \,\ \text{then} \,\ P = A^{-1} \\
$$

__Proof.__ <br>
Trivial.

##### Theorem.1.4.
Square matrix $A, \,\ B, \,\ C$에 대하여, $A$가 가역행렬일때, 

$$
\text{If} \,\ [A \quad B] \cong_R [I \quad C], \,\ \text{then} \,\ C = A^{-1}B
$$

__Proof.__ <br>
Trivial.

##### Theorem.1.5.
$\text{If} \,\ A \,\ \text{and} \,\ B \,\ \text{are} \,\ n\text{-degree square matrices, then followings are true.} $

$$
\text{(1)} \quad Tr(AB) = Tr(BA) \\
\text{(2)} \quad Tr(PAP^{-1}) = Tr(A) \\
$$

__Proof.__ <br>
Trivial.

##### Definition.1.3. Gauss-Jordan Elimination and Gauss Elimination
Forward substitution을 통해서 어떤 행렬을 ref(row echelon form)으로 변환하는 과정을 Gauss Elimination이라고 하고, <br>
Back substitution까지 진행하여 어떤 행렬을 rref(reduced row echelon form으로 변환하는 과정을 Gauss-Jordan Elimination이라고 한다.


##### Definition.1.4. Matrix Decomposition
Matrix Decomposition은 어떤 Matrix를 여러 행렬들의 곱으로 표현하는 것을 의미한다. <br>
이는 Computational convenience, analytic simplicity를 목적으로 가진다.

---

##### Application.1.1. LU Decomposition
$ \text{Let} \,\ m \times n \,\  \text{matrix} \,\ A.$<br>
$ \text{By Gauss Elimination, We can get matrix} \,\ U. $<br>
$ \text{Then} \,\ E_p \cdots E_1 A = U $<br>
$ L = (E_p \cdots E_1)^{-1} $<br><br>

##### Ex)

$$
A = 
\begin{bmatrix}
2 & 4 & -1 & 5 & -2 \\
-4 & -5 & 3 & -8 & 1 \\
2 & -5 & -4 & 1 & 8 \\
-6 & 0 & 7 & -3 & 1 \\
\end{bmatrix} 
\cong
\begin{bmatrix}
2 & 4 & -1 & 5 & -2 \\
0 & 3 & 1 & 2 & -3 \\
0 & -9 & -3 & -4 & 10 \\
0 & 12 & 4 & 12 & -5 \\
\end{bmatrix} 
\cong
\begin{bmatrix}
2 & 4 & -1 & 5 & -2 \\
0 & 3 & 1 & 2 & -3 \\
0 & 0 & 0 & 2 & 1 \\
0 & 0 & 0 & 4 & 7 \\
\end{bmatrix} 
\cong
\begin{bmatrix}
2 & 4 & -1 & 5 & -2 \\
0 & 3 & 1 & 2 & -3 \\
0 & 0 & 0 & 2 & 1 \\
0 & 0 & 0 & 0 & 5 \\
\end{bmatrix} = U
$$

$$
L_{C_1} = \frac{1}{2} \begin{bmatrix} 2 \\ -4 \\ 2 \\ -6 \end{bmatrix}, \,\ 
L_{C_2} = \frac{1}{3} \begin{bmatrix} 0 \\ 3 \\ -9 \\ 12 \end{bmatrix}, \,\ 
L_{C_3} = \frac{1}{2} \begin{bmatrix} 0 \\ 0 \\ 2 \\ 4 \end{bmatrix}, \,\ 
L_{C_4} = \frac{1}{5} \begin{bmatrix} 0 \\ 0 \\ 0 \\ 5 \end{bmatrix}. 
$$

$$
\text{Therefore, } \,\ L = 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\
1 & -3 & 1 & 0 \\
-3 & 4 & 2 & 1 \\
\end{bmatrix} 
$$

Suppose we have to solve $ A\mathbf{x} = \mathbf{b} $.<br>
We can get $ A = LU $.<br>
Then 

$$
L\mathbf{d} = \mathbf{b} \\
U\mathbf{x} = \mathbf{d}
$$

In [8]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 4, -1, 5, -2],
              [-4, -5, 3, -8, 1],
              [2, -5, -4, 1, 8],
              [-6, 0, 7, -3, 1]])
P, L, U = lu(A) # P is permutating matrix(pivoting)
P, L, U

(array([[0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.66666667,  1.        ,  0.        ,  0.        ],
        [-0.33333333,  1.        ,  1.        ,  0.        ],
        [-0.33333333, -0.8       , -0.        ,  1.        ]]),
 array([[-6.00000000e+00,  0.00000000e+00,  7.00000000e+00,
         -3.00000000e+00,  1.00000000e+00],
        [ 0.00000000e+00, -5.00000000e+00, -1.66666667e+00,
         -6.00000000e+00,  3.33333333e-01],
        [ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16,
          6.00000000e+00,  8.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.00000000e-01, -1.40000000e+00]]))

---

#### 1.2. Determinants and Inverse Matrices

##### Theorem.1.6.
$n$차 정방행렬 $A = [a_{ij}]$에 대하여 $|A| = |A^\top|$

__Proof.__ <br>
Trivial.

##### Theorem.1.7.
$n$차 정방행렬 $A = [a_{ij}]$와 수 $k$에 대하여 
$|kA| = k^n|A|$

__Proof.__ <br>
Trivial.

##### Theorem.1.8.
두 행렬의 곱의 행렬식은 각각의 행렬식의 곱과 같다.

__Proof.__ <br>
Trivial.

##### Definition.1.5. Minor Determinant and Cofactor
$n$차 정방행렬 $A = [a_{ij}]$의 $i$번째 행과 $j$번째 열을 삭제하고 남은 $(n - 1)$차 정방행렬의 행렬식을 행렬 $A$의 $(i, j)-$Minor determinant이라고 하고 $M_{ij}$로 쓴다.<br>
또한 $M_{ij}$에 부호 $(-1)^{i + j}$를 곱한 $(-1)^{i + j}M_{ij}$를 행렬 $A$의 $(i, j)$-Cofactor라고 하고 $C_{ij}$로 쓴다.<br>
즉, 

$$
C_{ij} = (-1)^{i + j}M_{ij}
$$

##### Definition.1.6. Adjoint Matrix and Cofactor Matrix
$n$차 정방행렬 $A = [a_{ij}]$에서 $(i, j)$-Cofactor $C_{ij}$를 $(i, j)$ 성분으로 하는 행렬 $C = [C_{ij}]$의 전치행렬 $C^\top$를 $A$의 Adjoint matrix또는 여인수 행렬(Cofactor matrix)이라고 하며, $\text{adj}(A)$로 나타낸다.

$$
\text{adj}(A) = [C_{ij}]^\top = 
\begin{bmatrix}
C_{11} & C_{21} & \cdots & C_{n1} \\
C_{12} & C_{22} & \cdots & C_{n2} \\
\vdots & \vdots & \ddots & \vdots \\
C_{1n} & C_{2n} & \cdots & C_{nn} \\
\end{bmatrix}
$$


##### Theorem.1.9.
$n$차 정방행렬 $A = [a_{ij}]$에 대하여 다음이 성립한다. <br><br>

$\text{(1)} \quad \text{adj}(A)A = A\text{adj}(A) = |A|I_n$<br>
$\text{(2)} \quad A$가 정칙행렬일 필요충분조건은 $|A| \neq 0$이다.<br>
$\text{(3)} \quad A$가 정칙행렬이면 $A^{-1} = \frac{1}{|A|}\text{adj}(A)$이다.<br>

__Proof.__ <br>
Trivial.

##### Definition.1.7. Minor Determinant and Rank
$m \times n$행렬 $A$의 $m - r$개 행과 $n - r$개의 열을 제거하고 남은 $r$차의 정방행렬에 대한 행렬식을 $A$의 $r$차의 소행렬식(Minor determinant)이라고 한다.<br>
만약 $A$의 $r$차 소행렬식 중에서 $0$이 아닌 것이 적어도 하나 존재하고, $r$보다 큰 모든 $s(r < s)$에 대하여 소행렬식이 모두 $0$일때, $r$을 행렬 $A$의 계수(rank)라고 하고
$$
\text{rank}(A) = r
$$
이라고 나타낸다.

##### Theorem.1.10.
$\text{If} \,\ A \cong A^\prime, \,\ \text{then} \,\ \text{rank}(A) = \text{rank}(A^\prime)$

__Proof.__ <br>
Trivial.

##### Theorem.1.11.
행렬의 계수(rank)는 그 행렬의 rref에서 leading 1의 개수와 같다.

__Proof.__ <br>
Trivial.

#### 1.3. Rank and Solution of System of Linear Equation

연립 일차 방정식의 해의 종류는 다음과 같다.
- No solution
- Particular solution(Only one solution)
- Infinitely many solutions

##### Definition.1.8. Homogeneous System of Linear Equations
미지수 $x_1, \,\ x_2, \,\ \cdots, \,\ x_n$에 관한 연립일차방정식

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = 0 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = 0 \\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\; \vdots  \\
a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n = 0 \\
\end{cases}
$$
을 Homogeneous System of Linear Euation이라고 한다.

Homogeneous System of Linear Equation은 다음과 같은 해를 가진다.
- Trivial solution
- Infinitely many solution including trivial solution.

##### Theorem.1.12.
$ \text{In homogeneous system of linear equations, if} \,\ m < n, \,\ \text{then the system have infinitely many solutions.} $


__Proof.__ <br>
Trivial.

##### Theorem.1.13.
행렬 $A_{m \times n}, \,\ \mathbf{b}_{m \times 1} = [b_1 \,\ b_2 \,\ \cdots \,\ b_m]^\top, \,\ \mathbf{x}_{n \times 1} = [x_1 \,\ x_2 \,\ \cdots \,\ x_n]^\top$에 대하여 연립일차방정식 $A\mathbf{x} = \mathbf{b}$가 해를 가질 필요충분조건은

$$
\text{rank}(A) = \text{rank}([A \quad B])
$$
이며, $A\mathbf{x} = \mathbf{b}$가 해를 가지는 경우는 다음과 같다.

- $\text{If} \,\ \text{rank}(A) = \text{rank}([A \quad B]) = n, \,\ \text{then} \,\ A\mathbf{x} = \mathbf{b} \,\ \text{have a particular solution.}$
- $\text{If} \,\ \text{rank}(A) = \text{rank}([A \quad B]) < n, \,\ \text{then} \,\ A\mathbf{x} = \mathbf{b} \,\ \text{have infinitely many solutions.}$

__Remark)__ <br>
1. $\text{If} \,\ \text{rank}(A) \neq \text{rank}([A \quad B]), \,\ \text{then} \,\ \nexists \,\ \text{solution of} \,\ A\mathbf{x} = \mathbf{b}$.
2. $\text{If} \,\ \text{rank}(A) = \text{rank}([A \quad B]) = n, \,\ \text{then} \,\ \exists^1 \,\ \text{solution of} \,\ A\mathbf{x} = \mathbf{b}$.
3. $\text{If} \,\ \text{rank}(A) = \text{rank}([A \quad B]) < n, \,\ \text{then} \,\ \exists^\infty \,\ \text{solution of} \,\ A\mathbf{x} = \mathbf{b}$.

__Proof.__ <br>
Trivial.

##### Theorem.1.14.
$ m \times n $행렬 $A$에 대하여 만약 $m < n$이면 동차연립일차방정식 $A\mathbf{x} = \mathbf{0}$는 무한히 많은 해를 가진다.

__Proof.__ <br>
Trivial.

##### Theorem.1.15.
$n$차 정방행렬 $A$를 계수행렬로 가지는 동차연립일차방정식 $A\mathbf{x} = \mathbf{0}$가 자명해가 아닌 해를 가질 필요충분조건은 $\text{rank}(A) < n$이다.

__Proof.__ <br>
Trivial.